version: "3"
services:
  postgres:
    image: postgres:13.3
    hostname: postgres
    container_name: postgres
    networks:
      - mxm_backend
    environment:
      POSTGRES_DB: "mxm"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq
    networks:
      - mxm_backend
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    ports:
      - 15672:15672
      - 5672:5672
  auth-api:
    image: auth-api
    container_name: auth-api
    restart: always
    networks:
      - mxm_backend
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
networks:
  mxm_backend: